### ISSUE TITLE
twice for paper Geometry Guided Adversarial Facial Expression Synthesis

### ISSUE THREAD

**Issue by huqiaoping** [EvelynFan/AWESOME-FER#1]
twice for paper "Geometry Guided Adversarial Facial Expression Synthesis"
you can delete one

**Comment by EvelynFan** [comment]
> twice for paper "Geometry Guided Adversarial Facial Expression Synthesis"
> you can delete one

Thanks for the reminder :)

**Comment by EvelynFan** [comment]
> twice for paper "Geometry Guided Adversarial Facial Expression Synthesis"
> you can delete one

Has deleted one.
