### ISSUE TITLE
Cartoon FER Dataset

### ISSUE THREAD

**Issue by ardaegeunlu** [EvelynFan/AWESOME-FER#11]
This [dataset ](http://grail.cs.washington.edu/projects/deepexpr/ferg-db.html) from UW might be helpful to some.

Cheers. 🥂

**Comment by EvelynFan** [comment]
> This [dataset ](http://grail.cs.washington.edu/projects/deepexpr/ferg-db.html) from UW might be helpful to some.
> 
> Cheers. 🥂
Very interesting dataset. Have added it to the list. 🥂
