### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by marisancans** [EvelynFan/AWESOME-FER#12]
Hello, this is a really helpful repo.
I found a link that is not working in:
FER Datasets
    Facial Expression Research Group Database (FERG-DB)
The page opens and says "That page can't be found."

**Comment by EvelynFan** [comment]
> Hello, this is a really helpful repo.
> I found a link that is not working in:
> FER Datasets
> Facial Expression Research Group Database (FERG-DB)
> The page opens and says "That page can't be found."

Thanks for reporting this issue. Now the link works.
