### ISSUE TITLE
Paper to be added

### ISSUE THREAD

**Issue by fabawi** [EvelynFan/AWESOME-FER#14]
Siqueira, Henrique, Sven Magg, and Stefan Wermter. "Efficient facial feature learning with wide ensemble-based convolutional neural networks." AAAI (2020).

**Comment by fabawi** [comment]
https://www2.informatik.uni-hamburg.de/wtm/publications/2020/SMW20/SMW20.pdf

**Comment by EvelynFan** [comment]
> Siqueira, Henrique, Sven Magg, and Stefan Wermter. "Efficient facial feature learning with wide ensemble-based convolutional neural networks." AAAI (2020).

Have added this AAAI 2020 paper. Thanks for your help :)
