### ISSUE TITLE
Asking for advice

### ISSUE THREAD

**Issue by chenjun19950315** [EvelynFan/AWESOME-FER#15]
Hello, since I started to do facial expression recognition, I would like to consult what you think is a good solution for facial expression recognition and what good papers do you recommend, thank you!

**Comment by EvelynFan** [comment]
> Hello, since I started to do facial expression recognition, I would like to consult what you think is a good solution for facial expression recognition and what good papers do you recommend, thank you!

From my point of view,  the survey paper "Deep Facial Expression Recognition: A Survey"  published by IEEE Transactions on Affective Computing 2020 is a good one for learning FER. It introduces the famous FER datasets, the general pipeline of deep FER systems, recent deep learning-based FER methods, etc. See if you can learn something from it :)
