### ISSUE TITLE
I want to know what's the meaning fo symbol 💫, which looks cute. Dose it mean the artical is novel?

### ISSUE THREAD

**Issue by kiva12138** [EvelynFan/AWESOME-FER#17]
I want to know what's the meaning fo symbol 💫, which looks cute. Dose it mean the artical is novel?

**Comment by EvelynFan** [comment]
> I want to know what's the meaning fo symbol 💫, which looks cute. Dose it mean the artical is novel?

Hh, not exactly. In the beginning, I just used this symbol 💫, to indicate how much I can benefit from this paper. Later on, I didn't use such ratings. Of course, the rating is just a personal opinion. You may ignore the symbol :)
