### ISSUE TITLE
Ask question about 10-fold subject-independent cross validation 

### ISSUE THREAD

**Issue by ZoieMo** [EvelynFan/AWESOME-FER#4]
I have a great interest in emotion recognition. But I have questions on 10-fold subject-independent cross validation.
How do you conduct the 10-fold subject-independent cross validation on CK+ database? Do you divide 118 persons into 10 fold and take turns to use 106 persons' expressions as training set, the rest 12 persons' expressions as testing set? Do you save the best test accuracy in each fold and average them as the final result?

你是如何在CK+数据库上进行10折交叉验证实验的呢？你是把118个人平均分为10份，每次轮流取106个人的全部表情作为训练集，剩下12个人的全部表情作为测试集吗？你最后的准确率是怎么计算的呢？是取每一折的收敛时候的准确率来计算，还是取最好的准确率来计算最后的平均准确率呢？

**Comment by EvelynFan** [comment]
> I have a great interest in emotion recognition. But I have questions on 10-fold subject-independent cross validation.
> How do you conduct the 10-fold subject-independent cross validation on CK+ database? Do you divide 118 persons into 10 fold and take turns to use 106 persons' expressions as training set, the rest 12 persons' expressions as testing set? Do you save the best test accuracy in each fold and average them as the final result?
> 
> 你是如何在CK+数据库上进行10折交叉验证实验的呢？你是把118个人平均分为10份，每次轮流取106个人的全部表情作为训练集，剩下12个人的全部表情作为测试集吗？你最后的准确率是怎么计算的呢？是取每一折的收敛时候的准确率来计算，还是取最好的准确率来计算最后的平均准确率呢？

Hi, ZoieMo.

10-fold cross validation means the model is trained with 9-folds and then used to predict the expressions in the remaining fold. I think they usually run the experiments 10 times and regard the average of ten results as the final accuracy, not the best accuracy.

**Comment by EvelynFan** [comment]
> > I have a great interest in emotion recognition. But I have questions on 10-fold subject-independent cross validation.
> > How do you conduct the 10-fold subject-independent cross validation on CK+ database? Do you divide 118 persons into 10 fold and take turns to use 106 persons' expressions as training set, the rest 12 persons' expressions as testing set? Do you save the best test accuracy in each fold and average them as the final result?
> > 你是如何在CK+数据库上进行10折交叉验证实验的呢？你是把118个人平均分为10份，每次轮流取106个人的全部表情作为训练集，剩下12个人的全部表情作为测试集吗？你最后的准确率是怎么计算的呢？是取每一折的收敛时候的准确率来计算，还是取最好的准确率来计算最后的平均准确率呢？
> 
> Hi, ZoieMo.
> 
> 10-fold cross validation means the model is trained with 9-folds and then used to predict the expressions in the remaining fold. I think they usually run the experiments 10 times and regard the average of ten results as the final accuracy, not the best accuracy.

I will close this issue for now, if you have other problem, feel free to reopen this issue :)
