### ISSUE TITLE
A new survey on automatic facial action unit analysis

### ISSUE THREAD

**Issue by Sampson-Lee** [EvelynFan/AWESOME-FER#8]
A comprehensive survey on automatic facial action unit analysis[https://link.springer.com/article/10.1007%2Fs00371-019-01707-5]

**Comment by EvelynFan** [comment]
> A comprehensive survey on automatic facial action unit analysis[https://link.springer.com/article/10.1007%2Fs00371-019-01707-5]

Thanks. But maybe it's better for us to focus on top conferences or journals?

**Comment by Sampson-Lee** [comment]
> > A comprehensive survey on automatic facial action unit analysis[https://link.springer.com/article/10.1007%2Fs00371-019-01707-5]
> 
> Thanks. But maybe it's better for us to focus on top conferences or journals?

Yes, it is more reasonable to focus on top conferences or journals.
